version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    target-branch: "development"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
