[package]
name = "krustie"
version = "0.1.4"
authors = ["Emre Can Corapci"]
description = "A simple HTTP server"
homepage = "https://github.com/emrecancorapci/krustie"
repository = "https://github.com/emrecancorapci/krustie"
license = "MIT"
edition = "2021"

[dependencies]
flate2 = "1.0.30"
