[package]
name = "krustie"
version = "0.1.8"
description = "Krustie is a backend framework written in Rust. Currently, it is a work in progress and not yet ready for production use."
categories = ["network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/emrecancorapci/krustie"
repository = "https://github.com/emrecancorapci/krustie"
authors = ["Emre Can Corapci"]
license = "MIT"
edition = "2021"

[dependencies]
flate2 = "1.0.30"
serde_json = "1.0.120"
