[package]
name = "krustie"
version = "0.1.13"
description = "Krustie is a simple and easy-to-use backend framework."
categories = ["network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/emrecancorapci/krustie"
repository = "https://github.com/emrecancorapci/krustie"
authors = ["Emre Can Corapci"]
license = "MIT"
edition = "2021"

[dependencies]
dyn-clone = "1.0.17"
flate2 = "1.0.33"
regex = "1.10.6"
serde_json = "1.0.128"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1
strip = true
